services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/avantsoft_app
      - gems_cache:/avantsoft_app/vendor/bundle
    ports:
      - "${RAILS_PORT}:${RAILS_INTERNAL_PORT:-3000}"
    environment:
      - RAILS_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_INTERNAL_PORT=${DB_INTERNAL_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${RAILS_INTERNAL_PORT:-3000}"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    user: avantsoft

  db:
    image: postgres:17.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_INTERNAL_PORT:-5432}"

volumes:
  postgres_data:
  gems_cache:
