---
openapi: 3.0.1
info:
  title: Avantsoft API V1
  version: v1
  description: API para gerenciamento de quadros e círculos
paths:
  "/api/v1/circles":
    get:
      summary: Lista círculos dentro de um raio
      tags:
      - Circles
      parameters:
      - name: center_x
        in: query
        required: true
        description: Coordenada X do centro
        schema:
          type: number
      - name: center_y
        in: query
        required: true
        description: Coordenada Y do centro
        schema:
          type: number
      - name: radius
        in: query
        required: true
        description: Raio em centímetros
        schema:
          type: number
      - name: frame_id
        in: query
        required: false
        description: ID do quadro (opcional)
        schema:
          type: integer
      responses:
        '200':
          description: Lista de círculos retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Circle"
        '422':
          description: Radius inválido
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
  "/api/v1/circles/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    put:
      summary: Atualiza um círculo
      tags:
      - Circles
      parameters: []
      responses:
        '200':
          description: Círculo atualizado com sucesso
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Circle"
        '422':
          description: Erro de validação
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
        '404':
          description: Círculo não encontrado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                circle:
                  type: object
                  properties:
                    x_axis:
                      type: number
                    y_axis:
                      type: number
                    diameter:
                      type: number
    delete:
      summary: Remove um círculo
      tags:
      - Circles
      responses:
        '204':
          description: Círculo removido com sucesso
        '404':
          description: Círculo não encontrado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
  "/api/v1/frames":
    post:
      summary: Cria um novo quadro
      tags:
      - Frames
      parameters: []
      responses:
        '201':
          description: Quadro criado com sucesso
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Frame"
        '422':
          description: Erro de validação
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                frame:
                  type: object
                  properties:
                    x_axis:
                      type: number
                      example: 0
                    y_axis:
                      type: number
                      example: 0
                    width:
                      type: number
                      example: 100
                    height:
                      type: number
                      example: 100
                    circles:
                      type: array
                      items:
                        type: object
                        properties:
                          x_axis:
                            type: number
                          y_axis:
                            type: number
                          diameter:
                            type: number
                    circles_attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          x_axis:
                            type: number
                          y_axis:
                            type: number
                          diameter:
                            type: number
                          _destroy:
                            type: boolean
                          id:
                            type: integer
                  required:
                  - x_axis
                  - y_axis
                  - width
                  - height
  "/api/v1/frames/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retorna detalhes de um quadro
      tags:
      - Frames
      responses:
        '200':
          description: Detalhes do quadro retornados com sucesso
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/FrameWithMetrics"
        '404':
          description: Quadro não encontrado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    delete:
      summary: Remove um quadro
      tags:
      - Frames
      responses:
        '204':
          description: Quadro removido com sucesso
        '422':
          description: Erro ao remover quadro com círculos
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
        '404':
          description: Quadro não encontrado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
  "/api/v1/frames/{id}/circles":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    post:
      summary: Adiciona um círculo ao quadro
      tags:
      - Frames
      parameters: []
      responses:
        '201':
          description: Círculo criado com sucesso
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Circle"
        '422':
          description: Erro de validação
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
        '404':
          description: Quadro não encontrado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                circle:
                  type: object
                  properties:
                    x_axis:
                      type: number
                      example: 50
                    y_axis:
                      type: number
                      example: 50
                    diameter:
                      type: number
                      example: 20
                  required:
                  - x_axis
                  - y_axis
                  - diameter
servers:
- url: http://localhost:3000
  description: Servidor de desenvolvimento
components:
  schemas:
    Frame:
      type: object
      description: Representa um quadro retangular no sistema
      required:
      - x_axis
      - y_axis
      - width
      - height
      properties:
        id:
          type: integer
          description: Identificador único do quadro
          example: 1
          readOnly: true
        x_axis:
          type: number
          format: decimal
          description: Coordenada X do canto superior esquerdo do quadro
          example: 100.5
          minimum: 0
        y_axis:
          type: number
          format: decimal
          description: Coordenada Y do canto superior esquerdo do quadro
          example: 200.75
          minimum: 0
        width:
          type: number
          format: decimal
          description: Largura do quadro em centímetros
          example: 150.0
          minimum: 0.01
        height:
          type: number
          format: decimal
          description: Altura do quadro em centímetros
          example: 100.0
          minimum: 0.01
        total_circles:
          type: integer
          description: Número total de círculos dentro do quadro
          example: 3
          minimum: 0
          readOnly: true
        created_at:
          type: string
          format: datetime
          description: Data e hora de criação do quadro
          example: '2025-09-17T02:42:13.630Z'
          readOnly: true
        updated_at:
          type: string
          format: datetime
          description: Data e hora da última atualização do quadro
          example: '2025-09-17T02:42:13.630Z'
          readOnly: true
    Circle:
      type: object
      description: Representa um círculo dentro de um quadro
      required:
      - x_axis
      - y_axis
      - diameter
      - frame_id
      properties:
        id:
          type: integer
          description: Identificador único do círculo
          example: 1
          readOnly: true
        x_axis:
          type: number
          format: decimal
          description: Coordenada X do centro do círculo
          example: 125.25
          minimum: 0
        y_axis:
          type: number
          format: decimal
          description: Coordenada Y do centro do círculo
          example: 175.5
          minimum: 0
        diameter:
          type: number
          format: decimal
          description: Diâmetro do círculo em centímetros
          example: 20.0
          minimum: 0.01
        frame_id:
          type: integer
          description: ID do quadro ao qual o círculo pertence
          example: 1
        created_at:
          type: string
          format: datetime
          description: Data e hora de criação do círculo
          example: '2025-09-17T02:42:13.630Z'
          readOnly: true
        updated_at:
          type: string
          format: datetime
          description: Data e hora da última atualização do círculo
          example: '2025-09-17T02:42:13.630Z'
          readOnly: true
    FrameMetrics:
      type: object
      description: Métricas calculadas dos círculos dentro de um quadro
      properties:
        total_circles:
          type: integer
          description: Número total de círculos no quadro
          example: 3
          minimum: 0
        highest_circle_position:
          type: number
          format: decimal
          description: Coordenada Y do círculo mais alto (menor valor Y)
          example: 150.0
          nullable: true
        lowest_circle_position:
          type: number
          format: decimal
          description: Coordenada Y do círculo mais baixo (maior valor Y)
          example: 200.0
          nullable: true
        leftmost_circle_position:
          type: number
          format: decimal
          description: Coordenada X do círculo mais à esquerda (menor valor X)
          example: 120.0
          nullable: true
        rightmost_circle_position:
          type: number
          format: decimal
          description: Coordenada X do círculo mais à direita (maior valor X)
          example: 180.0
          nullable: true
    FrameWithMetrics:
      type: object
      description: Quadro com suas métricas de círculos
      allOf:
      - "$ref": "#/components/schemas/Frame"
      - type: object
        properties:
          metrics:
            "$ref": "#/components/schemas/FrameMetrics"
    CircleSearchParams:
      type: object
      description: Parâmetros para busca de círculos por raio
      required:
      - center_x
      - center_y
      - radius
      properties:
        center_x:
          type: number
          format: decimal
          description: Coordenada X do centro da busca
          example: 150.0
          minimum: 0
        center_y:
          type: number
          format: decimal
          description: Coordenada Y do centro da busca
          example: 175.0
          minimum: 0
        radius:
          type: number
          format: decimal
          description: Raio de busca em centímetros
          example: 50.0
          minimum: 0.01
        frame_id:
          type: integer
          description: ID do quadro para filtrar círculos (opcional)
          example: 1
    Error:
      type: object
      description: Resposta de erro da API
      required:
      - errors
      properties:
        errors:
          type: array
          description: Lista de mensagens de erro
          items:
            type: string
            example: Círculo deve caber completamente dentro do quadro
          example:
          - Círculo deve caber completamente dentro do quadro
          - Círculo não pode tocar outro círculo no mesmo quadro
    ValidationError:
      type: object
      description: Erro de validação com detalhes específicos
      properties:
        errors:
          type: object
          description: Erros organizados por campo
          additionalProperties:
            type: array
            items:
              type: string
          example:
            x_axis:
            - não pode estar em branco
            diameter:
            - deve ser maior que 0
